Improved exception handling
BMDSoftware/play2-memcached pull request #1
Opened 2023-08-22 14:15 UTC by Rui-Jesus

This contribution changes the behavior of cache.get when a throwable is detected. Before, it would not handle the exception, which could cause issues for clients of this API.

2023-08-23 13:30 UTC, Enet4 commented on plugin/src/main/play_2.4/com/github/mumoshu/play2/memcached/MemcachedCacheApi.scala
> +          logger.error("An error has occured while getting the value from memcached. ct=" + ct , e)
I wonder if we should also do this for write operations such as `set` and `remove`.

2023-08-23 14:47 UTC, Rui-Jesus commented on plugin/src/main/play_2.4/com/github/mumoshu/play2/memcached/MemcachedCacheApi.scala
> +          logger.error("An error has occured while getting the value from memcached. ct=" + ct , e)
I think it should yes.

2023-08-29 09:21 UTC, Enet4 commented
Deployed for testing as version `0.7.2-BMD-1-SNAPSHOT`.

2023-08-29 14:06 UTC, Enet4 requested changes
As mentioned this afternoon, we will take this moment to also update the whole component to use Play 2.5. I have just pushed branch `play-2.5` to our remote repository with the necessary build/test changes. All you need to do is rebase these changes on top of it, discarding any changes to `Build.scala` and `build.properties` made here.

2023-08-29 14:35 UTC, Rui-Jesus commented
> As mentioned this afternoon, we will take this moment to also update the whole component to use Play 2.5. I have just pushed branch `play-2.5` to our remote repository with the necessary build/test changes. All you need to do is rebase this PR on top of it, discarding any changes to `Build.scala` and `build.properties` made here.

Done.

2023-08-29 15:50 UTC, Enet4 commented
Published as `0.8.1-BMD-2-SNAPSHOT`

2023-09-20 09:38 UTC, Enet4 reviewed
Jus suggesting a few changes to the error messages to be leaner (fixes typos, and we already know that they refer to memcached from the logger name).

2023-09-20 09:38 UTC, Enet4 commented on plugin/src/main/play_2.5/com/github/mumoshu/play2/memcached/MemcachedCacheApi.scala
> +          logger.error("An error has occured while getting the value from memcached: " + t.getMessage)
```suggestion
          logger.error("Failed to get the value in cache: " + t.getMessage)
```

2023-09-20 09:38 UTC, Enet4 commented on plugin/src/main/play_2.5/com/github/mumoshu/play2/memcached/MemcachedCacheApi.scala
> +          logger.error("An error has occured while setting the value memcached: " + t.getMessage)
```suggestion
          logger.error("Failed to set the value in cache: " + t.getMessage)
```

2023-09-20 09:38 UTC, Enet4 commented on plugin/src/main/play_2.5/com/github/mumoshu/play2/memcached/MemcachedCacheApi.scala
> +          logger.error("An error has occured while removing the value from memcached: " + t.getMessage)
```suggestion
          logger.error("Failed to remove the value from cache: " + t.getMessage)
```

2023-09-20 10:31 UTC, Enet4 approved these changes
We've been using this version of the client for a while, and it seems pretty solid. I think we're ready for an internal patch release. 👍

2023-09-20 10:32 UTC, merged